program z3;
var a,b : integer;

begin
  readln(a,b);
  if ((a = 90) and (b = 90))then
    writeln('прямоугольник')
  else
  begin
    if (a + b = 180)then
      writeln('паралеллограмм');
    if ((a = 90) or (b = 90))then
      writeln('прямоугольная трапеция');
    if ( (a<>90) and (b <> 90) and (a+b <> 180) and (a<>b) )then
      writeln('простая трапеция');
    if (a = b)then
      writeln('равнобедренная трапеция');
  end;
end.
